import {test} from 'node:test';
import assert from 'node:assert/strict';
import bs58 from 'bs58';
import nacl from 'tweetnacl';
import {Keypair,TransactionMessage,VersionedTransaction,SystemProgram} from '@solana/web3.js';
import {createApp} from '../app.mjs';
import {providers,SOL,USDC} from '../providers.mjs';
async function harness(t) {
  let time=Date.now(), executions=0;
  const key=Keypair.generate(),other=Keypair.generate();
  function transaction() {const message=new TransactionMessage({payerKey:key.publicKey,recentBlockhash:Keypair.generate().publicKey.toBase58(),instructions:[SystemProgram.transfer({fromPubkey:key.publicKey,toPubkey:other.publicKey,lamports:1})]}).compileToV0Message();return Buffer.from(new VersionedTransaction(message).serialize()).toString('base64');}
  const provider={portfolio:async wallet=>({wallet,sol:1,tokens:[]}),candles:async()=>[{c:1},{c:2},{c:1.5}],rpc:async()=>({value:[]}),voice:async()=>({requires_review:true}),order:async body=>({...body,venue:'jupiter',data:{},transaction:transaction(),in_amount:body.amount,out_amount:'1200000',minimum_receive:'1190000',request_id:'r'}),execute:async()=>{executions++;return {signature:'test',status:'confirmed'};}};
  const server=createApp({env:{APP_ORIGIN:'http://localhost:5173'},provider,now:()=>time}).listen(0,'127.0.0.1');
  await new Promise(r=>server.once('listening',r));t.after(()=>server.close());
  const base=`http://127.0.0.1:${server.address().port}`;
  async function request(path,body,token,method=body?'POST':'GET',origin) {const r=await fetch(base+'/api/gadget/'+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{}),...(origin?{Origin:origin}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:r.headers.get('content-type')?.includes('json')?await r.json():Buffer.from(await r.arrayBuffer())};}
  async function login(who=key){const challenge=(await request('challenge',{wallet:who.publicKey.toBase58()})).data;const signature=bs58.encode(nacl.sign.detached(Buffer.from(challenge.message),who.secretKey));const result=await request('device-auth',{nonce:challenge.nonce,signature});return {token:result.data.device_token,challenge,signature};}
  return {key,other,request,login,advance:ms=>time+=ms,executions:()=>executions};
}
test('auth is signature-verified, replay resistant, revocable and expires',async t=>{const h=await harness(t);assert.equal((await h.request('portfolio')).status,401);const {token,challenge,signature}=await h.login();assert.equal((await h.request('device-auth',{nonce:challenge.nonce,signature})).status,401);assert.equal((await h.request('portfolio',null,token)).status,200);await h.request('session',null,token,'DELETE');assert.equal((await h.request('portfolio',null,token)).status,401);const second=await h.login();h.advance(3600001);assert.equal((await h.request('portfolio',null,second.token)).status,401);});
test('cross-wallet intents rejected, altered transaction rejected, duplicate submit locked',async t=>{const h=await harness(t),a=await h.login(),b=await h.login(h.other);const q=(await h.request('quote',{input_mint:SOL,output_mint:USDC,amount:'10000000'},a.token)).data;assert.equal((await h.request('intent',{quote_id:q.quote_id},b.token)).status,409);const intent=(await h.request('intent',{quote_id:q.quote_id},a.token)).data;const signed=VersionedTransaction.deserialize(Buffer.from(intent.unsigned_tx,'base64'));signed.sign([h.key]);const changed=VersionedTransaction.deserialize(Buffer.from(intent.unsigned_tx,'base64'));changed.message.recentBlockhash=Keypair.generate().publicKey.toBase58();changed.sign([h.key]);assert.equal((await h.request('submit',{intent_id:intent.intent_id,signed_tx:Buffer.from(changed.serialize()).toString('base64')},a.token)).status,400);const body={intent_id:intent.intent_id,signed_tx:Buffer.from(signed.serialize()).toString('base64')};assert.equal((await h.request('submit',body,a.token)).status,200);assert.equal((await h.request('submit',body,a.token)).status,409);assert.equal(h.executions(),1);});
test('quote expiry and signature required before submission',async t=>{const h=await harness(t),{token}=await h.login();const q=(await h.request('quote',{input_mint:SOL,output_mint:USDC,amount:'1'},token)).data;const intent=(await h.request('intent',{quote_id:q.quote_id},token)).data;assert.equal((await h.request('submit',{intent_id:intent.intent_id,signed_tx:intent.unsigned_tx},token)).status,401);h.advance(30001);assert.equal((await h.request('intent',{quote_id:q.quote_id},token)).status,409);assert.equal(h.executions(),0);});
test('origin restriction, private RPC allowlist and chart formats',async t=>{const h=await harness(t);assert.equal((await h.request('status',null,null,'GET','https://evil.example')).status,403);const {token}=await h.login();assert.equal((await h.request('rpc',{method:'sendTransaction',params:[]},token)).status,400);const jpeg=await h.request('chart?mint='+SOL,null,token);assert.equal(jpeg.status,200);assert.equal(jpeg.data.subarray(0,2).toString('hex'),'ffd8');const raw=await h.request('chart?mint='+SOL+'&format=rgb565',null,token);assert.equal(raw.data.length,240*240*2);});
test('provider sends integer amounts and header auth; errors never expose secrets',async()=>{let seen;const p=providers({DFLOW_API_KEY:'test-secret'},async(url,options)=>{seen={url,options};return {ok:true,json:async()=>({transaction:'abc',inputMint:SOL,outputMint:USDC,inAmount:'100',outAmount:'123',otherAmountThreshold:'120'})};});await p.order({wallet:SOL,input_mint:SOL,output_mint:USDC,amount:'100',venue:'dflow'});assert.equal(seen.options.headers['x-api-key'],'test-secret');assert.ok(!seen.url.includes('test-secret'));await assert.rejects(()=>p.order({wallet:SOL,input_mint:SOL,output_mint:USDC,amount:'0.1',venue:'dflow'}),/base units/);const broken=providers({HELIUS_RPC_URL:'https://secret.example/?api-key=secret'},async()=>{throw Error('https://secret.example/?api-key=secret');});await assert.rejects(()=>broken.rpc('getBalance',[]),e=>!e.message.includes('secret'));});
test('Alchemy RPC URL takes precedence and device bearer cannot submit',async t=>{let seen;const p=providers({RPC_URL:'https://alchemy.example/v2/server-secret',HELIUS_RPC_URL:'https://helius.example'},async(url)=>{seen=url;return {ok:true,json:async()=>({result:{value:7}})};});assert.deepEqual(await p.rpc('getBalance',[SOL]),{value:7});assert.equal(seen,'https://alchemy.example/v2/server-secret');const h=await harness(t),{token}=await h.login();const device=(await h.request('device-token',{},token)).data;assert.equal((await h.request('portfolio',null,device.device_token)).status,200);assert.equal((await h.request('submit',{intent_id:'anything',signed_tx:'anything'},device.device_token)).status,403);});
